Fix for e.g. NoMethodError: undefined method `value_for_database' for "DDBIdentifier":String
(cherry picked from commit 3613c4d2c1cff17b5efa835c615ba310df93970a)